library(shiny)
songs <- read.csv("songs.csv")
ui <- fluidPage(
  titlePanel("Songs dataset", windowTitle = "Songs dataset"),
  sidebarLayout(
    sidebarPanel(
      selectInput("FromID", "From",
                  choices = c("1990", "1991", "1992", "1993", "1994", "1995", "1996",
                              "1997", "1998", "1999", "2000", "2001", "2002", "2003",
                              "2004", "2005", "2006", "2007", "2008", "2009", "2010")),
      selectInput("ToID", "To",
                  choices = c("1990", "1991", "1992", "1993", "1994", "1995", "1996",
                              "1997", "1998", "1999", "2000", "2001", "2002", "2003",
                              "2004", "2005", "2006", "2007", "2008", "2009", "2010")),
      selectInput("VariableID", "Parameter on Y-axis",
                  choices = c("timesignature_confidence", "loudness", "tempo", "tempo_confidence", "key",
                              "key_confidence", "energy", "pitch", "timbre_0_min", "timbre_0_max",
                              "timbre_1_min", "timbre_1_max", "timbre_2_min", "timbre_2_max", "timbre_3_min",
                              "timbre_3_max", "timbre_4_min", "timbre_4_max", "timbre_5_min", "timbre_5_max",
                              "timbre_6_min", "timbre_6_max", "timbre_7_min", "timbre_7_max",
                              "timbre_8_min", "timbre_8_max", "timbre_9_min", "timbre_9_max", "timbre_10_min",
                              "timbre_10_max", "timbre_11_min", "timbre_11_max", "Top10")),
      selectInput("artistInput", "artistname",
                   choices = c( "A Day to Remember",   
                                "Adam Lambert", 
                                "Analog Rebellion",
                                "Artists For Haiti"  ,
                                "B.o.B",  
                                "Britney Spears",
                                "Butch Walker",        
                                "David Guetta",       
                                "Dimmu Borgir",       
                                "DragonForce",
                                "Drake"   ,       
                                "Drowning Pool",  
                                "Eels",           
                                "Emily Osment", 
                                "Eminem",         
                                "Enrique Iglesias" ,  
                                 "Far*East Movement", 
                                "Fear Factory",   
                                "Flo Rida" ,    
                                "Glee Cast",          
                                 "Iyaz",  
                                "Jason Derulo" ,  
                                "Jay Sean",       
                                "Jay-Z + Alicia Keys",
                                "Jay-Z + Mr. Hudson", 
                                "Justin Bieber",
                                "Kashmir"     ,     
                                "Kate Nash",          
                                 "Katy Perry" ,
                                "Ke$ha",    
                                "Kevin Rudolf" ,    
                                "La Roux"     ,       
                                "Lady Antebellum",     
                                "Lady Gaga",        
                                "Lifehouse"     ,   
                                "Lil Scrappy",        
                                  "Lil Wayne",                                        
                                  "Ludacris"  ,                                       
                                  "Manafest"   ,                                      
                                  "Mike Posner" ,                                     
                                  "Miley Cyrus"  ,                                    
                                  "Nadine"        ,                                   
                                 "October Tide"    ,                                 
                                 "Outlawz"          ,                                
                                  "Overkill"         ,                                
                                 "Owl City"           ,                              
                                 "Reba"                ,                             
                                  "Rihanna"             ,                             
                                  "Sara Bareilles"       ,                            
                                  "Shearwater"            ,                           
                                 "Shout Out Louds"         ,                         
                                 "Super Junior"             ,                        
                                 "Superchunk"                ,                       
                                 "Taio Cruz"                  ,                      
                                  "Taylor Swift"               ,                      
                                  "The Bird and the Bee"        ,                     
                                  "The Black Eyed Peas"          ,                    
                                  "The Magnetic Fields"           ,                   
                                  "Travie McCoy"                   ,                  
                                 "Trey Songz"                       ,                
                                  "Usher"                            ,                
                                  "Various Artists"                   ,               
                                  "Young Money"                        ,              
                                  "Athlete"                             ,            
                                  "Band of Skulls"                      ,           
                                  "Beyonce"                             ,             
                                 "Carrie Underwood"                      ,           
                                 "Cheryl Cole"                            ,          
                                  "Ciara"                                  ,          
                                 "Cobra Starship"                           ,        
                                  "Coldplay"                                 ,        
                                 "Collective Soul"                            ,      
                                  "Creed"                                      ,      
                                  "Crooked X"                                   ,     
                                 "Family Force 5"                                ,   
                                 "Flight of the Conchords"                        ,  
                                  "Hannah Montana"                                 ,  
                                  "Hit the Lights"                                  , 
                                  "Ingrid Michaelson"                                ,
                                  "Jamie Foxx"                                       ,
                                 "Jason DeRulo"                                     ,
                                 "Jason Mraz"                                       ,
                                  "Jay-Z"                                            ,
                                  "Jeremih"                                          ,
                                  "Jordin Sparks"                                    ,
                                  "Julien-K"                                         ,
                                 "Kanye West"                                       ,
                                  "Kelly Clarkson"                                   ,
                                  "Keri Hilson"                                      ,
                                  "Kid Cudi"                                         ,
                                 "Kings Of Leon"                                    ,
                                 "Kris Allen"                                       ,
                                  "Lady GaGa"                                        ,
                                 "Linkin Park"                                      ,
                                 "Manchester Orchestra"                             ,
                                 "Mariah Carey"                                     ,
                                 "Merzbow"                                          ,
                                 "Mike Jones"                                       ,
                                 "MxPx"                                             ,
                                 "Nek"                                              ,
                                 "Newton Faulkner"                                  ,
                                 "Noah and the Whale"                               ,
                                 "Pilot Speed"                                      ,
                                 "Pitbull"                                          ,
                                 "Powerman 5000"                                    ,
                                 "Rancid"                                           ,
                                  "Red Light Company"                                ,
                                 "Saosin"                                           ,
                                 "Seabird"                                          ,
                                  "Sean Kingston"                                    ,
                                 "Shinedown"                                        ,
                                 "Silverstein"                                      ,
                                 "Slaughterhouse"                                   ,
                                 "Soulja Boy Tell 'em"                              ,
                                  "Sugar Ray"                                        ,
                                 "T.I."                                             ,
                                 "The All-American Rejects"                         ,
                                  "The Audition"                                     ,
                                  "The Fray"                                         ,
                                 "The Juan MacLean"                                 ,
                                  "Third Eye Blind"                                  ,
                                  "Umphrey's McGee"                                  ,
                                  "Various artists"                                  ,
                                 "VOTA"                                             ,
                                  "Whitney Houston"                                  ,
                                 "Woods"                                            ,
                                  "Yngwie Malmsteen"                                 ,
                                  "Akon"                                             ,
                                 "Alicia Keys"                                      ,
                                  "Anastacia"                                        ,
                                  "Andrea Bocelli"                                   ,
                                  "Black Kids"                                       ,
                                  "Brooks & Dunn"                                    ,
                                  "Buckcherry"                                       ,
                                 "Chris Brown"                                      ,
                                  "Christina Aguilera"                               ,
                                 "Colbie Caillat"                                   ,
                                 "Danity Kane"                                      ,
                                  "David Archuleta"                                  ,
                                 "David Cook"                                       ,
                                 "Demi Lovato & Joe Jonas"                          ,
                                 "Disfear"                                          ,
                                  "Dr. Dog"                                          ,
                                  "eMC"                                              ,
                                 "Estelle"                                          ,
                                 "Europe"                                           ,
                                  "Fergie"                                           ,
                                 "Finger Eleven"                                    ,
                                  "Fireflight"                                       ,
                                  "Flogging Molly"                                   ,
                                 "Haste the Day"                                    ,
                                  "Jay-Z & T.I."                                     ,
                                  "Jesse McCartney"                                  ,
                                  "John Mellencamp"                                  ,
                                  "Jonas Brothers"                                   ,
                                 "Joseph Williams"                                  ,
                                 "Kalmah"                                           ,
                                 "Kardinal Offishall"                               ,
                                 "Ken Block"                                        ,
                                  "Lenny Kravitz"                                    ,
                                  "Leona Lewis"                                      ,
                                  "Lil Mama"                                         ,
                                 "Lupe Fiasco"                                      ,
                                  "M.I.A."                                           ,
                                  "Madonna"                                          ,
                                 "Metro Station"                                    ,
                                 "Ministry and Co-Conspirators"                     ,
                                  "Nada Surf"                                        ,
                                  "Natasha Bedingfield"                              ,
                                  "Ne-Yo"                                            ,
                                  "Nickelback"                                       ,
                                 "Pink"                                             ,
                                  "Plants and Animals"                               ,
                                 "Plies"                                            ,
                                 "Ray J & Yung Berg"                                ,
                                 "Richard Marx"                                     ,
                                 "Shwayze"                                          ,
                                  "Snoop Dogg"                                       ,
                                  "Soulja Boy"                                       ,
                                  "Strapping Young Lad"                              ,
                                  "T-Pain"                                           ,
                                  "Taproot"                                          ,
                                 "Thao with the Get Down Stay Down"                 ,
                                  "The Game"                                         ,
                                  "The Pete Best Band"                               ,
                                  "The Pussycat Dolls"                               ,
                                 "The Smashing Pumpkins"                            ,
                                 "This Is Hell"                                     ,
                                 "Thursday"                                         ,
                                  "Timbaland"                                        ,
                                  "Trapt"                                            ,
                                  "Webbie"                                           ,
                                 "Yael Naim"                                        ,
                                  "50 Cent"                                          ,
                                  "Against Me!"                                      ,
                                  "Aly & AJ"                                         ,
                                 "Amy Winehouse"                                    ,
                                 "Another Animal"                                   ,
                                  "Aqueduct"                                         ,
                                 "August Burns Red"                                 ,
                                 "Avenged Sevenfold"                                ,
                                 "Avril Lavigne"                                    ,
                                 "Baby Bash"                                    ,
                                  "Beyonce & Shakira"                            ,    
                                 "Blaqk Audio"                                    ,  
                                 "Bone Thugs-N-Harmony"                            , 
                                 "Bone Thugs-n-Harmony"                             ,
                                  "Bow Wow"                                          ,
                                  "Bright Eyes"                                      ,
                                  "Carmen Rasmusen"                                  ,
                                 "Charlotte Hatherley"                              ,
                                  "Chrisette Michele"                                ,
                                 "Crime Mob"                                        ,
                                  "Dan Deacon"                                       ,
                                  "Dashboard Confessional"                           ,
                                  "Daughtry"                                         ,
                                 "Deerhoof"                                         ,
                                  "Diddy"                                            ,
                                  "Dixie Chicks"                                     ,
                                 "Dying Fetus"                                      ,
                                  "Epica"                                            ,
                                  "Fabolous"                                         ,
                                  "Gorilla Zoe"                                      ,
                                 "Gwen Stefani"                                     ,
                                  "Gym Class Heroes"                                 ,
                                 "Hinder"                                           ,
                                 "Hurricane Chris"                                  ,
                                  "J. Holiday"                                       ,
                                  "Jason Aldean"                                     ,
                                  "Jennifer Lopez"                                   ,
                                 "Jim Jones"                                        ,
                                  "Justin Timberlake"                                ,
                                  "Kenna"                                            ,
                                  "Keyshia Cole"                                     ,
                                  "Les Savy Fav"                                     ,
                                 "Lloyd"                                            ,
                                 "Maroon 5"                                         ,
                                  "McFly"                                            ,
                                 "Menomena"                                         ,
                                 "Mims"                                             ,
                                 "My Chemical Romance"                              ,
                                 "Nelly Furtado"                                    ,
                                 "No Angels"                                        ,
                                  "Of Montreal"                                      ,
                                  "Oysterband"                                       ,
                                  "Plain White Ts"                                  ,
                                  "Poison"                                           ,
                                  "Poison the Well"                                  ,
                                  "Puscifer"                                         ,
                                  "Relient K"                                        ,
                                  "Rich Boy"                                         ,
                                  "Rihanna & Sean Paul"                              ,
                                  "Scorpions"                                        ,
                                  "Shop Boyz"                                        ,
                                 "Sick Puppies"                                     ,
                                  "Silverchair"                                      ,
                                 "So They Say"                                      ,
                                  "Soilwork"                                         ,
                                 "Submersed"                                        ,
                                 "The Cliks"                                        ,
                                 "The Cult"                                         ,
                                  "The Flower Kings"                                 ,
                                  "The Operation M.D."                               ,
                                  "The Police"                                       ,
                                  "The Wildhearts"                                   ,
                                  "Tori Amos"                                        ,
                                 "Unk"                                              ,
                                  "Visions of Atlantis"                              ,
                                  "will.i.am"                                        ,
                                  "Wooden Stars"                                     ,
                                  "X-Clan"                                           ,
                                 "Ace Frehley"                                      ,
                                 "Angels & Airwaves"                                ,
                                  "Boards of Canada"                                 ,
                                  "Brian McKnight"                                   ,
                                  "Bubba Sparxxx"                                    ,
                                  "Built to Spill"                                   ,
                                  "Cascada"                                          ,
                                  "Cassie"                                           ,
                                 "Cat Power"                                        ,
                                 "Cellador"                                         ,
                                  "Chamillionaire"                                   ,
                                 "Chingy"                                           ,
                                 "Comets on Fire"                                   ,
                                  "D4L"                                              ,
                                 "Daniel Powter"                                    ,
                                  "Dave Burrell"                                     ,
                                  "DMC"                                              ,
                                  "Donavon Frankenreiter"                            ,
                                  "Duels"                                            ,
                                  "Evanescence"                                      ,
                                 "Field Mob"                                        ,
                                 "G. Love"                                          ,
                                 "Gnarls Barkley"                                   ,
                                  "Gossip"                                           ,
                                  "House of Lords"                                   ,
                                 "India.Arie"                                       ,
                                  "Isobel Campbell"                                  ,
                                 "James Blunt"                                      ,
                                 "Jessi Colter"                                     ,
                                  "Jibbs"                                            ,
                                 "Joe Satriani"                                     ,
                                  "John Mayer"                                       ,
                                  "JoJo"                                             ,
                                  "Juelz Santana"                                    ,
                                  "LeAnn Rimes"                                      ,
                                  "Lil Jon"                                          ,
                                  "LL Cool J"                                        ,
                                 "Los Lonely Boys"                                  ,
                                 "Lyfe Jennings"                                    ,
                                 "Mary J. Blige"                                    ,
                                 "Miss Kittin"                                      ,
                                  "Nelly"                                            ,
                                  "Nick Lachey"                                      ,
                                  "NOFX"                                             ,
                                 "Panic! At The Disco"                              ,
                                  "Paul Stanley"                                     ,
                                  "Rascal Flatts"                                    ,
                                 "Red Hot Chili Peppers"                            ,
                                 "Sean Paul"                                        ,
                                 "Shakira"                                          ,
                                 "Snow Patrol"                                      ,
                                  "Sparks"                                           ,
                                  "Styles P"                                         ,
                                 "Taylor Hicks"                                     ,
                                  "The Blow"                                         ,
                                 "The Red Jumpsuit Apparatus"                       ,
                                  "The Residents"                                    ,
                                  "The Zutons"                                       ,
                                  "Therapy?"                                         ,
                                  "Valencia"                                         ,
                                  "Weird Al Yankovic"                                ,
                                  "Willie Nile"                                      ,
                                  "Young Dro"                                        ,
                                 "Yung Joc"                                         ,
                                 "Aerosmith"                                        ,
                                 "American Hi-Fi"                                   ,
                                 "Amerie"                                           ,
                                 "Blockhead"                                        ,
                                  "Bo Bice"                                          ,
                                  "Bobby Valentino"                                  ,
                                 "Bruce Dickinson"                                  ,
                                  "Caribou"                                          ,
                                 "D.H.T."                                           ,
                                 "David Banner"                                     ,
                                  "Destinys Child"                                  ,
                                 "Erasure"                                          ,
                                  "Exodus"                                           ,
                                 "Fat Joe"                                          ,
                                  "Fort Minor"                                       ,
                                 "Frankie J"                                        ,
                                  "Gavin DeGraw"                                     ,
                                  "Green Day"                                        ,
                                  "Imogen Heap"                                      ,
                                  "Ja Rule"                                          ,
                                 "John Lennon"                                      ,
                                 "Kaiser Chiefs"                                    ,
                                 "Lagwagon"                                         ,
                                 "Life of Agony"                                    ,
                                  "Lil Jon & The East Side Boyz"                     ,
                                  "Limp Bizkit"                                      ,
                                  "Lindsay Lohan"                                    ,
                                 "Liz Phair"                                        ,
                                  "Mario"                                            ,
                                 "Missy Elliott"                                    ,
                                  "Pretty Ricky"                                     ,
                                  "Reggie and the Full Effect"                       ,
                                  "Rev. Run"                                         ,
                                 "Rob Thomas"                                       ,
                                  "Roger Miret and the Disasters"                    ,
                                  "Sarah Hudson"                                     ,
                                  "Spin Doctors"                                     ,
                                  "The New Pornographers"                            ,
                                  "The Rolling Stones"                               ,
                                  "Tom Vek"                                          ,
                                  "Transplants"                                      ,
                                 "Usher And Alicia Keys"                            ,
                                 "Utada"                                            ,
                                 "Violent Femmes"                                   ,
                                 "Weezer"                                           ,
                                  "Wilco"                                            ,
                                  "Will Smith"                                       ,
                                  "Young Jeezy"                                      ,
                                  "Ashlee Simpson"                                   ,
                                  "Autolux"                                          ,
                                 "Avoid One Thing"                                  ,
                                  "Beenie Man"                                       ,
                                  "Ben Harper"                                       ,
                                  "Ben Kweller"                                      ,
                                  "Bob Dylan"                                        ,
                                 "Brad Mehldau"                                     ,
                                  "Calexico"                                         ,
                                  "Candy Butchers"                                   ,
                                  "Cassidy"                                          ,
                                  "Christina Milian"                                 ,
                                  "Clay Aiken"                                       ,
                                  "D12"                                              ,
                                  "Dave Matthews Band"                               ,
                                  "Dead Kennedys"                                    ,
                                  "Dogs Die in Hot Cars"                             ,
                                  "Fantasia"                                         ,
                                  "George Harrison"                                  ,
                                  "Hoobastank"                                       ,
                                  "In Flames"                                        ,
                                  "J-Kwon"                                           ,
                                  "Jagged Edge"                                      ,
                                  "Jimmy Eat World"                                  ,
                                  "Juvenile"                                         ,
                                  "Kelis"                                            ,
                                 "Kevin Lyttle"                                     ,
                                 "Kidz Bop Kids"                                    ,
                                  "Le Tigre"                                         ,
                                  "Lil Flip"                                        ,
                                  "Lloyd Banks"                                      ,
                                 "Lostprophets"                                     ,
                                 "Mad Caddies"                                      ,
                                 "Manic Street Preachers"                           ,
                                 "Mario Winans"                                     ,
                                 "Marissa Nadler"                                   ,
                                  "Nina Sky"                                         ,
                                  "No Doubt"                                         ,
                                 "OutKast"                                          ,
                                  "Petey Pablo"                                      ,
                                 "Rogue Wave"                                       ,
                                 "Ron Sexsmith"                                     ,
                                  "Ruben Studdard"                                   ,
                                 "Rufus Wainwright"                                 ,
                                  "Rush"                                             ,
                                  "Saliva"                                           ,
                                  "Sarah Harmer"                                     ,
                                  "Steve Earle"                                      ,
                                 "Terror Squad"                                     ,
                                  "The Carpenters"                                   ,
                                 "The Hold Steady"                                  ,
                                 "The Killers"                                      ,
                                  "The Vines"                                        ,
                                  "Trans-Siberian Orchestra"                         ,
                                 "Trick Daddy"                                      ,
                                 "Twista"                                           ,
                                  "U2"                                               ,
                                  "Usher & Alicia Keys"                              ,
                                  "Ying Yang Twins"                                  ,
                                  "Zero 7"                                           ,
                                  "A Static Lullaby"                                 ,
                                  "American Idol Finalists"                          ,
                                  "Anthrax"                                          ,
                                  "Ashanti"                                          ,
                                  "Ben Folds"                                        ,
                                  "Bettie Serveert"                                  ,
                                  "Black Eyed Peas"                                  ,
                                  "Boo-Yaa T.R.I.B.E."                               ,
                                  "Busta Rhymes & Mariah Carey"                      ,
                                  "Carbon Leaf"                                      ,
                                  "Cex"                                              ,
                                  "Craig Morgan"                                     ,
                                  "Cult of Luna"                                     ,
                                  "Daft Punk"                                        ,
                                  "Eagles"                                           ,
                                  "Eisley"                                           ,
                                  "Erykah Badu"                                      ,
                                  "Ginuwine"                                         ,
                                 "Guster"                                           ,
                                  "Harry Connick"                                    ,
                                  "Kid Rock"                                         ,
                                  "Killah Priest"                                    ,
                                  "Kurt Elling"                                      ,
                                 "Lene Marlin"                                      ,
                                  "Lil Kim"                                         ,
                                  "Mark Owen"                                        ,
                                 "matchbox twenty"                                  ,
                                 "Meat Loaf"                                        ,
                                 "Melanie C"                                        ,
                                  "Michael Bubl_"                                    ,
                                  "Monica"                                           ,
                                 "Neal Morse"                                       ,
                                 "Nivea"                                            ,
                                 "O.A.R."                                           ,
                                 "Pharrell"                                         ,
                                 "Prefuse 73"                                       ,
                                 "R. Kelly"                                         ,
                                  "Rob Zombie"                                       ,
                                  "Ryan Malcolm"                                     ,
                                  "Santana"                                          ,
                                  "Spiritualized"                                    ,
                                 "The Jayhawks"                                     ,
                                  "Triumph"                                          ,
                                  "Tyrese"                                           ,
                                  "Uncle Kracker"                                    ,
                                  "Wellwater Conspiracy"                             ,
                                  "Year of the Rabbit"                               ,
                                  "YoungBloodZ"                                      ,
                                  "Aaliyah"                                          ,
                                 "Ace Troubleshooter"                               ,
                                  "Aimee Mann"                                       ,
                                  "Angie Martinez"                                   ,
                                  "Ash"                                              ,
                                  "Audioslave"                                       ,
                                  "Black Sabbath"                                    ,
                                 "Brandy"                                           ,
                                  "Buckethead"                                       ,
                                 "Camron"                                          ,
                                  "Chad Kroeger"                                     ,
                                 "Chris Isaak"                                      ,
                                 "Craig David"                                      ,
                                 "Crazy Town"                                       ,
                                 "Daniel Bedingfield"                               ,
                                 "Dave Davies"                                      ,
                                 "DJ Sammy & Yanou"                                 ,
                                  "Dream Theater"                                    ,
                                 "Entombed"                                         ,
                                 "Eve"                                              ,                               "Faith Hill"                                       ,
                                 "Hilary Duff"                                      ,
                                  "Jaheim"                                           ,
                                  "King Crimson"                                     ,
                                  "Kylie Minogue"                                    ,
                                  "Leonard Cohen"                                    ,
                                  "Lionel Richie"                                    ,
                                 "Lock Up"                                          ,
                                  "Michelle Branch"                                  ,
                                 "N.O.R.E."                                         ,
                                  "Napalm Death"                                     ,
                                  "P. Diddy"                                         ,
                                  "P. Diddy & Ginuwine"                              ,
                                  "Phantom Planet"                                   ,
                                 "Puddle Of Mudd"                                   ,
                                 "Sam Roberts"                                      ,
                                 "Soulfly"                                          ,
                                  "Styles"                                           ,
                                  "The Calling"                                      ,
                                  "The Chemical Brothers"                            ,
                                  "The Exploited"                                    ,
                                  "The Polyphonic Spree"                             ,
                                 "The Streets"                                      ,
                                  "The Tragically Hip"                               ,
                                 "They Might Be Giants"                             ,
                                  "Treble Charger"                                   ,
                                  "Truth Hurts"                                      ,
                                 "Tweet"                                            ,
                                  "Vanessa Carlton"                                  ,
                                 "Voodoo Glow Skulls"                               ,
                                  "Agnostic Front"                                   ,
                                  "Blu Cantrell"                                     ,
                                  "Buddy Guy"                                        ,
                                 "Case"                                             ,
                                  "City High"                                        ,
                                 "David Byrne"                                      ,
                                 "Daz Dillinger"                                    ,
                                 "Debelah Morgan"                                   ,
                                 "Dido"                                             ,
                                  "Dream"                                            ,
                                 "Edens Crush"                                     ,
                                  "Embrace"                                          ,
                                 "Enya"                                             ,
                                 "Evergrey"                                         ,
                                 "Incubus"                                          ,
                                 "Janet"                                            ,
                                 "Kool and the Gang"                                ,
                                  "Kurupt"                                           ,
                                 "Lil Romeo"                                       ,
                                 "Mercury Rev"                                      ,
                                 "Michael Jackson"                                  ,
                                 "Moloko"                                           ,
                                 "Mystic"                                           ,
                                 "O-Town"                                           ,
                                 "Ocean Colour Scene"                               ,
                                 "Ryan Adams"                                       ,
                                 "S Club 7"                                         ,
                                  "Shaggy"                                           ,
                                 "Staind"                                           ,
                                 "Stone Temple Pilots"                              ,
                                 "t.A.T.u."                                         ,
                                 "Tamia"                                            ,
                                 "The Ex"                                           ,
                                 "Train"                                            ,
                                 "Trick Pony"                                       ,
                                 "Witchery"                                         ,
                                 "98 Degrees"                                       ,
                                 "Arch Enemy"                                       ,
                                  "Backstreet Boys"                                  ,
                                  "Baha Men"                                         ,
                                 "Blaque"                                           ,
                                 "Blink-182"                                        ,
                                  "Catch 22"                                         ,
                                  "Chris Rea"                                        ,
                                  "Chumbawamba"                                      ,
                                 "David Coverdale"                                  ,
                                  "Deftones"                                         ,
                                 "Donell Jones"                                     ,
                                 "Eiffel 65"                                        ,
                                 "Elastica"                                         ,
                                 "Five"                                             ,
                                 "Hanson"                                           ,
                                 "Jessica Simpson"                                  ,
                                  "Joe"                                              ,
                                 "Kenny G"                                          ,
                                 "Lonestar"                                         ,
                                 "Macy Gray"                                        ,
                                  "Marc Anthony"                                     ,
                                 "Melvins"                                          ,
                                 "Montell Jordan"                                   ,
                                  "Next"                                             ,
                                 "Nine Days"                                        ,
                                  "Old Mans Child"                                  ,
                                  "Poe"                                              ,
                                 "Rickie Lee Jones"                                 ,
                                 "Ruff Endz"                                        ,
                                 "Samantha Mumba"                                   ,
                                 "Savage Garden"                                    ,
                                 "Sisqo"                                            ,
                                 "Sonique"                                          ,
                                 "soulDecision"                                     ,
                                  "The Gathering"                                    ,
                                 "The Presidents of the United States of America"   ,
                                  "Vertical Horizon"                                 ,
                                 "Wyclef Jean"                                      ,
                                  "Yes"                                              ,
                                  "Alex Lloyd"                                       ,
                                 "Big Sugar"                                        ,
                                 "Bis"                                              ,
                                  "Black Label Society"                              ,
                                  "Blur"                                             ,
                                 "Case "                                            ,
                                 "Cher"                                             ,
                                 "Chevelle"                                         ,
                                  "Divine"                                           ,
                                  "Dokken"                                           ,
                                 "Dr. Dooom"                                        ,
                                 "Eagle-Eye Cherry"                                 ,
                                  "Edguy"                                            ,
                                  "Faith Evans"                                      ,
                                  "Goldfinger"                                       ,
                                  "Guns N' Roses"                                    ,
                                 "Handsome Boy Modeling School"                     ,
                                  "Hypocrisy"                                        ,
                                  "Jeff Beck"                                        ,
                                 "Jesse Powell"                                     ,
                                  "Jewel"                                            ,
                                  "Joey McIntyre"                                    ,
                                  "Jordan Knight"                                    ,
                                 "JT Money"                                         ,
                                 "Kevon Edmonds"                                    ,
                                 "KMFDM"                                            ,
                                  "Lauryn Hill"                                      ,
                                  "Led Zeppelin"                                     ,
                                  "Len"                                              ,
                                  "Lou Bega"                                         ,
                                 "Maxwell"                                          ,
                                  "Naughty By Nature"                                ,
                                 "P.O.D."                                           ,
                                  "Paul McCartney"                                   ,
                                  "Pearl Jam"                                        ,
                                  "Phish"                                            ,
                                  "Ricky Martin"                                     ,
                                 "Sarah McLachlan"                                  ,
                                 "Shania Twain"                                     ,
                                 "Shawn Mullins"                                    ,
                                 "Silkk the Shocker"                                ,
                                 "Sinergy"                                          ,
                                 "Sixpence None The Richer"                         ,
                                 "Smash Mouth"                                      ,
                                  "Smog"                                             ,
                                 "Static-X"                                         ,
                                  "Texas"                                            ,
                                 "Tim McGraw"                                       ,
                                 "TLC"                                              ,
                                  "Total"                                            ,
                                 "Various"                                          ,
                                 "Vice Squad"                                       ,
                                 "Ace of Base"                                      ,
                                  "Air"                                              ,
                                 "Alkaline Trio"                                    ,
                                  "All Saints"                                       ,
                                 "Ani DiFranco"                                     ,
                                 "Bane"                                             ,
                                 "Barenaked Ladies"                                 ,
                                  "Bizzy Bone"                                       ,
                                  "Boyz II Men"                                      ,
                                 "Brandy "                                          ,
                                 "Brandy & Monica"                                  ,
                                 "Bruce Hornsby"                                    ,
                                 "Busta Rhymes"                                     ,
                                  "B_la Fleck and the Flecktones"                    ,
                                  "Celine Dion"                                      ,
                                  "Deana Carter"                                     ,
                                 "Deborah Cox"                                      ,
                                 "Deep Purple"                                      ,
                                  "Dru Hill"                                         ,
                                  "Edwin McCain"                                     ,
                                 "Eric Clapton"                                     ,
                                  "Fuel"                                             ,
                                  "Fun Lovin Criminals"                             ,
                                  "Goo Goo Dolls"                                    ,
                                 "Hole"                                             ,
                                 "Inoj"                                             ,
                                 "Jennifer Paige"                                   ,
                                  "Jerry Cantrell"                                   ,
                                  "K-Ci "                                            ,
                                  "K-Ci & JoJo"                                      ,
                                 "K.P. & Envyi"                                     ,
                                  "Kristin Hersh"                                    ,
                                 "Lord Tariq & Peter Gunz"                          ,
                                  "LSG"                                              ,
                                 "Marcy Playground"                                 ,
                                 "Mase"                                             ,
                                 "Monifah"                                          ,
                                  "Montell Jordan Feat. Master P & Silkk The Shocker",
                                  "Nicole"                                           ,
                                 "Plastilina Mosh"                                  ,
                                  "Public Announcement"                              ,
                                  "Queen Latifah"                                    ,
                                  "Robyn"                                            ,
                                  "RZA"                                              ,
                                  "Spice Girls"                                      ,
                                  "Sylk-E. Fyne"                                     ,
                                  "Tatyana Ali"                                      ,
                                 "The Bouncing Souls"                               ,
                                 "Uncle Sam"                                        ,
                                  "Van Halen"                                        ,
                                 "Voices Of Theory"                                 ,
                                 "Willie Nelson"                                    ,
                                  "Xscape"                                           ,
                                 "Zebrahead"                                        ,
                                  "Allure"                                           ,
                                  "Anal Cunt"                                        ,
                                 "Aqua"                                             ,
                                  "Az Yet"                                           ,
                                  "Babyface"                                         ,
                                  "BLACKstreet ("                                    ,
                                  "Blonde Redhead"                                   ,
                                  "Blues Traveler"                                   ,
                                  "Changing Faces"                                   ,
                                  "Cornershop"                                       ,
                                 "Foxy Brown"                                       ,
                                 "Great Big Sea"                                    ,
                                  "Keith Sweat"                                      ,
                                  "Mark Morrison"                                    ,
                                  "Meredith Brooks"                                  ,
                                  "Merril Bainbridge"                                ,
                                  "Millencolin"                                      ,
                                 "No Use for a Name"                                ,
                                  "Old 97's"                                         ,
                                 "Pat Benatar"                                      ,
                                  "Paula Cole"                                       ,
                                 "Puff Daddy & Faith Evans"                         ,
                                  "Reel Big Fish"                                    ,
                                 "Ric Ocasek"                                       ,
                                  "Robert Miles"                                     ,
                                  "Rome"                                             ,
                                  "Sheryl Crow"                                      ,
                                 "Simple Minds"                                     ,
                                  "Somethin' For The People"                         ,
                                 "The Apples in Stereo"                             ,
                                  "The Beach Boys"                                   ,
                                 "The Jam"                                          ,
                                 "The Notorious B.I.G."                             ,
                                 "The Verve Pipe"                                   ,
                                  "Third Day"                                        ,
                                  "Toni Braxton"                                     ,
                                  "Billy Bragg"                                      ,
                                  "Butthole Surfers"                                 ,
                                 "Catherine Wheel"                                  ,
                                 "D'Angelo"                                         ,
                                  "Dark Tranquillity"                                ,
                                 "Deep Blue Something"                              ,
                                 "Donna Lewis"                                      ,
                                 "Everything But The Girl"                          ,
                                 "George Michael"                                   ,
                                  "Jennifer Love Hewitt"                             ,
                                  "La Bouche"                                        ,
                                  "Mariah Carey & Boyz II Men"                       ,
                                 "Metallica"                                        ,
                                  "New Edition"                                      ,
                                  "Nirvana"                                          ,
                                  "No Mercy"                                         ,
                                  "Oasis"                                            ,
                                 "Prince"                                           ,
                                  "Quad City DJ's"                                   ,
                                 "Shawn Colvin"                                     ,
                                  "SWV"                                              ,
                                 "The Beatles"                                      ,
                                  "The Tony Rich Project"                            ,
                                  "Tracy Chapman"                                    ,
                                  "Travis Tritt"                                     ,
                                 "Warrant"                                          ,
                                  "Adina Howard"                                     ,
                                 "Alanis Morissette"                                ,
                                 "All-4-One"                                        ,
                                 "Atari Teenage Riot"                               ,
                                 "BLACKstreet"                                      ,
                                  "Blessid Union Of Souls"                           ,
                                 "Bon Jovi"                                         ,
                                  "Brownstone"                                       ,
                                  "Bryan Adams"                                      ,
                                  "Carly Simon"                                      ,
                                 "Deep Forest"                                      ,
                                 "Del Amitri"                                       ,
                                 "Dionne Farris"                                    ,
                                 "Dishwalla"                                        ,
                                 "Energy Orchard"                                   ,
                                 "Everclear"                                        ,
                                  "Groove Theory"                                    ,
                                 "Hootie & The Blowfish"                            ,
                                 "Janet Jackson"                                    ,
                                 "Joan Osborne"                                     ,
                                 "Jon B."                                           ,
                                 "Luniz"                                            ,
                                 "Melissa Etheridge"                                ,
                                  "Method Man"                                       ,
                                 "MoKenStef"                                        ,
                                 "Natalie Merchant"                                 ,
                                 "Nicki French"                                     ,
                                 "Real McCoy"                                       ,
                                 "Sophie B. Hawkins"                                ,
                                 "Soul For Real"                                    ,
                                  "Swans"                                            ,
                                 "Take That"                                        ,
                                 "Teenage Fanclub"                                  ,
                                 "The Innocence Mission"                            ,
                                 "The Tea Party"                                    ,
                                 "Ace Of Base"                                      ,
                                 "Barry Manilow"                                    ,
                                 "Beck"                                             ,
                                 "Boston"                                           ,
                                 "Boz Scaggs"                                       ,
                                 "Cake"                                             ,
                                 "Coolio"                                           ,
                                 "Craig Mack"                                       ,
                                 "Crash Test Dummies"                               ,
                                 "Da Brat"                                          ,
                                 "Des'ree"                                          ,
                                 "Domino"                                           ,
                                 "DRS"                                              ,
                                 "Enigma"                                           ,
                                 "Immature"                                         ,
                                 "Jon Secada"                                       ,
                                 "King's X"                                         ,
                                 "Luther Vandross "                                 ,
                                 "Mayhem"                                           ,
                                 "Michael Bolton"                                   ,
                                 "Sade"                                             ,
                                 "Salt-N-Pepa"                                      ,
                                 "Sugar"                                            ,
                                 "Tag Team"                                         ,
                                 "Talisman"                                         ,
                                 "Tevin Campbell"                                   ,
                                 "The Cranberries"                                  ,
                                 "The Sea and Cake"                                 ,
                                 "Warren G"                                         ,
                                 "Arrested Development"                             ,
                                 "Billy Joel"                                       ,
                                 "Bobby Brown"                                      ,
                                 "Bruce Springsteen"                                ,
                                 "Dr. Dre"                                          ,
                                 "Duran Duran"                                      ,
                                 "Firehose"                                         ,
                                 "Gabrielle"                                        ,
                                 "George Strait"                                    ,
                                 "H-Town"                                           ,
                                 "Haddaway"                                         ,
                                 "Heart"                                            ,
                                 "Heavy D & the Boyz"                               ,
                                 "Infectious Grooves"                               ,
                                 "Inner Circle"                                     ,
                                 "James"                                            ,
                                 "Jodeci"                                           ,
                                 "Morphine"                                         ,
                                 "Oleta Adams"                                      ,
                                 "Onyx"                                             ,
                                 "Orchestral Manoeuvres in the Dark"                ,
                                 "P.M. Dawn"                                        ,
                                 "Paperboy"                                         ,
                                 "Pennywise"                                        ,
                                 "Pete Townshend"                                   ,
                                 "Prince And The New Power Generation"              ,
                                 "Robin S."                                         ,
                                 "Rod Stewart"                                      ,
                                 "Shai"                                             ,
                                 "Silk"                                             ,
                                 "Snap"                                             ,
                                 "Snow"                                             ,
                                 "Soul Asylum"                                      ,
                                 "The Cure"                                         ,
                                 "The Roots"                                        ,
                                 "Toby Keith"                                       ,
                                 "Tony! Toni! Ton_!"                                ,
                                 "various artists"                                  ,
                                 "Wreckx-N-Effect"                                  ,
                                 "Zhane"                                            ,
                                 "Amy Grant"                                        ,
                                 "Atlantic Starr"                                   ,
                                 "Billy Ray Cyrus"                                  ,
                                 "CeCe Peniston"                                    ,
                                 "Color Me Badd"                                    ,
                                 "Elton John"                                       ,
                                 "En Vogue"                                         ,
                                 "Firehouse"                                        ,
                                 "Genesis"                                          ,
                                 "House Of Pain"                                    ,
                                 "Iced Earth"                                       ,
                                 "Joe Public"                                       ,
                                 "Kris Kross"                                       ,
                                 "Marky Mark "                                      ,
                                 "Michelle Shocked"                                 ,
                                 "Mint Condition"                                   ,
                                 "Mr. Big"                                          ,
                                 "Neil Young"                                       ,
                                 "Paula Abdul"                                      ,
                                 "Pavement"                                         ,
                                 "Queen"                                            ,
                                 "Roy Orbison"                                      ,
                                 "Selena"                                           ,
                                 "Shanice"                                          ,
                                 "Sir Mix-A-Lot"                                    ,
                                 "Sister Souljah"                                   ,
                                 "Suicidal Tendencies"                              ,
                                 "Technotronic"                                     ,
                                 "The Cover Girls"                                  ,
                                 "The Dead Milkmen"                                 ,
                                 "The Heights"                                      ,
                                 "The Lemonheads"                                   ,
                                 "The Mighty Mighty Bosstones"                      ,
                                 "Tom Cochrane"                                     ,
                                 "Ugly Kid Joe"                                     ,
                                 "Vanessa Williams"                                 ,
                                 "Aaron Neville"                                    ,
                                 "Another Bad Creation"                             ,
                                 "Babes in Toyland"                                 ,
                                 "Bette Midler"                                     ,
                                 "Black Box"                                        ,
                                 "Bonnie Raitt"                                     ,
                                 "C+C Music Factory"                                ,
                                 "Cathedral"                                        ,
                                 "Cathy Dennis"                                     ,
                                 "Chesney Hawkes"                                   ,
                                 "Corina"                                           ,
                                 "Curtis Stigers"                                   ,
                                 "Damn Yankees"                                     ,
                                 "Divinyls"                                         ,
                                 "EMF"                                              ,
                                 "Enuff Znuff"                                     ,
                                 "Gerardo"                                          ,
                                 "Gloria Estefan"                                   ,
                                 "Hi-Five"                                          ,
                                 "Huey Lewis and the News"                          ,
                                 "INXS"                                             ,
                                 "Jesus Jones"                                      ,
                                 "Karyn White"                                      ,
                                 "Londonbeat"                                       ,
                                 "Luis Miguel"                                      ,
                                 "Luther Vandross"                                  ,
                                 "Martika"                                          ,
                                 "Michael W. Smith"                                 ,
                                 "Monster Magnet"                                   ,
                                 "Natural Selection"                                ,
                                 "Nelson"                                           ,
                                 "Nia Peeples"                                      ,
                                 "Queensryche"                                      ,
                                 "R.E.M."                                           ,
                                 "Ralph Tresvant"                                   ,
                                 "Rick Astley"                                      ,
                                 "Roxette"                                          ,
                                 "Seal"                                             ,
                                 "Spirit of the West"                               ,
                                 "Stevie B"                                         ,
                                 "Sting"                                            ,
                                 "Styx"                                             ,
                                 "Surface"                                          ,
                                 "Tara Kemp"                                        ,
                                 "Tesla"                                            ,
                                 "The KLF"                                          ,
                                 "Throwing Muses"                                   ,
                                 "Timmy T."                                         ,
                                 "Tom Petty and the Heartbreakers"                  ,
                                 "Tracie Spencer"                                   ,
                                 "UB40"                                             ,
                                 "Vanilla Ice"                                      ,
                                 "Wilson Phillips"                                  ,
                                 "AC/DC"                                            ,
                                 "After 7"                                          ,
                                 "Al B. Sure!"                                      ,
                                 "Alannah Myles"                                    ,
                                 "Alias"                                            ,
                                 "Bad English"                                      ,
                                 "Bell Biv Devoe"                                   ,
                                 "Biz Markie"                                       ,
                                 "Calloway"                                         ,
                                 "Candyman"                                         ,
                                 "Cannibal Corpse"                                  ,
                                 "Chicago"                                          ,
                                 "Death"                                            ,
                                 "Death Angel"                                      ,
                                 "Deee-Lite"                                        ,
                                 "Depeche Mode"                                     ,
                                 "Dino"                                             ,
                                 "Expose"                                           ,
                                 "Extreme"                                          ,
                                 "Faith No More"                                    ,
                                 "Ian Gillan"                                       ,
                                 "Jody Watley"                                      ,
                                 "Johnny Gill"                                      ,
                                 "Judas Priest"                                     ,
                                 "Kiss"                                             ,
                                 "Linear"                                           ,
                                 "Lisa Stansfield"                                  ,
                                 "Los Lobos"                                        ,
                                 "Lou Gramm"                                        ,
                                 "Mark Lanegan"                                     ,
                                 "Maxi Priest"                                      ,
                                 "Milli Vanilli"                                    ,
                                 "Motley Crue"                                      ,
                                 "New Kids On The Block"                            ,
                                 "Paul Young"                                       ,
                                 "Pebbles"                                          ,
                                 "Phil Collins"                                     ,
                                 "Ramones"                                          ,
                                 "Seduction"                                        ,
                                 "Skid Row"                                         ,
                                 "Skinny Puppy"                                     ,
                                 "Soul II Soul"                                     ,
                                 "Sweet Sensation"                                  ,
                                 "Taylor Dayne"                                     ,
                                 "The B-52 s"                                       ,
                                 "The Las"                                         ,
                                 "The Mission"                                      ,
                                 "The Stranglers"                                   ,
                                 "The Time"                                         ,
                                 "Tom Petty"                                        ,
                                 "Tony Toni Tone",                                   
                                 "Tyler Collins",                                    
                                 "XTC",                                              
                                 "Y&T"),
                   selected = "Y&T")
    ),
    mainPanel(
      plotOutput("coolplot"),
      br(), br(),
      tableOutput("results")
    )
  )
)

library(ggplot2)
library(dplyr)
server <- function(input, output) {
  filtered <- reactive({
    songs %>%
      filter(year >= input$FromID,
             year <= input$ToID,
             artistname == input$artistInput
             #var = input$VariableID
      )
  })
  output$coolplot <- renderPlot({
    ggplot(filtered(), aes(year, energy)) +
      geom_point()
  })
  output$results <- renderTable({
    filtered()
  })
}

shinyApp(ui = ui, server = server)